before_install: eval $(curl https://travis-perl.github.io/init) --auto
dist: trusty
install: cpan-install Storable
language: perl
perl:
  - "5.6"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.24-mb"
  - "5.24-thr"
  - "dev"
sudo: false
