name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

        # All supported Perl versions except latest.
        perl: [
          '5.6',  '5.8',  '5.10', '5.12', '5.14', '5.16', '5.18', '5.20',
          '5.22', '5.24', '5.26', '5.28', '5.30'
        ]

        # Variants of the latest Perl.
        include:
          - os: macos-latest

          - os: windows-latest

          - name: ' (ithread)'
            ithread: true

          - name: ' (no memcached)'
            no-memcached: true

          # This is effectively our normal one, with xt ran at the end.
          - name: ' (xt)'
            xt: true

    runs-on: ${{ matrix.os }}

    name: v${{ matrix.perl }} on ${{ matrix.os }}${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2

      - if: ${{ !matrix.no-memcached }}
        uses: KeisukeYamashita/memcahed-actions@v1

      - uses: shogo82148/actions-setup-perl@v1
        with:
          multi-thread: ${{ matrix.ithread }}
          perl-version: ${{ matrix.perl }}

      - run: perl -v

      - run: make test

      - if: ${{ matrix.xt }}
        run: |
          cpanm -n Test::Pod Test::Pod::Coverage
          prove -blv xt
